board/urls.py
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "board"
urlpatterns = [
    path("", views.board_and_task, name="board_and_task"),
    path("task_delete/", views.displayBoard, name="displayBoard"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hometouser/urls.py
from django.urls import path
from . import views

app_name = "hometouser"
urlpatterns = [
    path("", views.index, name="index"),
    path("make-account/", views.make_account, name="make_account"),
    path("<str:display_name>/welcome/", views.home, name="home"),
    path("login/", views.login_user, name="login"),
    path("logged-out/", views.logout_view, name="logout")
]

kanbanboardProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("hometouser.urls")),
    path('board/', include("board.urls")),
    path('', include('board.urls')),
    path('list/', include('list.urls')),
]

list/urls.py
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "list"
urlpatterns = [
    path("", views.list_view, name="list_view"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

board/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    category =  models.CharField(primary_key = True, max_length=20)
    color = models.CharField(max_length=20)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.category}"

class Task(models.Model):
    name = models.CharField(primary_key = True, max_length=50)
    description = models.CharField(max_length=200)
    due_date = models.DateTimeField("time task is due")
    user_on_task = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"for {self.user.username} is: {self.name}"

board/forms.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from .models import Category, Task

COLORS = (
    ("#ADD8E6", "Blue"),
    ("#7CA37C", "Green"),
    ("#CBC3E3", "Purple"),
    ("#ff9194", "Red"),
)

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'due_date', 'user_on_task', 'category']
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['category'].queryset = Category.objects.filter(user=user)

class CategoryForm(forms.ModelForm):
    color = forms.ChoiceField(choices=COLORS)
    class Meta:
        model = Category
        fields = ['category', 'color']

board/views.py
from django.shortcuts import render, redirect
from .forms import TaskForm, CategoryForm
from .models import Task, Category
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
from django.contrib import messages

# Create your views here.

def board_and_task(request):

    if request.method == 'POST':
        if 'submitTask' in request.POST:
            taskForm = TaskForm(request.POST, prefix='task')
            categoryForm = CategoryForm(prefix='category')
            if taskForm.is_valid():
                task = Task(
                    name = taskForm.cleaned_data['name'],
                    description = taskForm.cleaned_data['description'],
                    due_date = taskForm.cleaned_data['due_date'],
                    user_on_task = taskForm.cleaned_data['user_on_task'],
                    category = taskForm.cleaned_data['category']
                )
                task.user = request.user
                task.save()
            
        elif 'submitCategory' in request.POST:
            categoryForm = CategoryForm(request.POST, prefix='category')
            taskForm = TaskForm(prefix='task')
            if categoryForm.is_valid():
                username = request.user
                category = Category(
                    category = categoryForm.cleaned_data['category'],
                    color = categoryForm.cleaned_data['color'],
                    user = username
                )
                
                category.save()
    else:
        # only make the empty forms once rather than at the top
        taskForm = TaskForm(prefix="task", user=request.user)
        categoryForm = CategoryForm(prefix="category")
    # pass these in for use in html
    categories = Category.objects.all()
    tasks = Task.objects.all()
    context = {'taskForm' : taskForm, 'categoryForm' : categoryForm, 'tasks' : tasks, 'categories' : categories}

    return render(request, "board/board.html", context)

def displayBoard(request):
    # if there is a get request to task_delete/ 
    if request.method == "GET":
        # gets id of the data passed in from js
        task_id = request.GET.get("task_to_delete")
        if task_id:
            try:
                task = Task.objects.get(pk=task_id)
                task.delete()
                # triggers success in js 
                return JsonResponse({"status" : "success"})
            except Task.DoesNotExist:
                # the rest trigger errors in js
                return JsonResponse({"status": "error", "message": "Task not found"}, status=404)
        else:
            return JsonResponse({"status": "error", "message": "No task id provided"}, status=400)
    return JsonResponse({"status": "error", "message": "Invalid request method"}, status=405)

board/templates/board/board.html
{% load crispy_forms_tags %} {% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Board View</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary py-5">
      <div class="container-fluid">
        <a class="navbar-brand"> Board View for {{user.username}} </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-tem"></li>
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'hometouser:home' display_name=user.username%}"
                >Home</a
              >
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                id="views"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Views
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="/board/">Board</a></li>
                <li><a class="dropdown-item" href="/list">List</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="#">About</a></li>
              </ul>
            </li>
          </ul>
          <a
            class="btn btn-outline-danger"
            href="{% url 'hometouser:logout' %}"
          >
            Logout
          </a>
        </div>
      </div>
    </nav>
    <div class="ms-5 d-flex justify-content-sm-start justify-content-center mt-5">
      <a
        class="link-secondary btn btn-outline-dark"
        href="{% url 'hometouser:home' display_name=user.username%}"
        >Go Back</a
      >
      <button
        type="button"
        class="btn btn-primary ms-3"
        id="task"
        data-toggle="modal"
        data-target="#taskModal"
        name="submitTask"
      >
        Create Task
      </button>
      <button
        type="button"
        class="btn btn-primary ms-3"
        id="category"
        data-toggle="modal"
        data-target="#categoryModal"
        name="submitCategory"
      >
        Create Category
      </button>
    </div>
    <!-- Modal -->
    <div
      class="modal fade"
      id="categoryModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="categoryModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="categoryModalLabel">Create a new category</h5>
          </div>
          <div class="modal-body">
            <form
              id="createTask"
              method="POST"
              action="{%url 'board:board_and_task'%}"
            >
              {% csrf_token %} {{ categoryForm|crispy }}
              <input
                class="btn btn-success"
                type="submit"
                value="Submit"
                name="submitCategory"
              />
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
    <div
      class="modal fade"
      id="taskModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="taskModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="taskModalLabel">
              Enter the task to complete.
            </h5>
          </div>
          <div class="modal-body">
            <div class="d-flex justify-content-center">
              <form
                id="createTask"
                method="POST"
                action="{%url 'board:board_and_task'%}"
              >
                {% csrf_token %} {{ taskForm|crispy }}
                <input
                  class="btn btn-success"
                  type="submit"
                  value="Submit"
                  name="submitTask"
                />
              </form>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      {% for category in categories %} {%if user.username == category.user.username%}
      <div class="col-md ps-lg-5 ms-2 me-2 pe-lg-5">
        <h1
          style="background-color:{{ category.color }};"
          class="mt-5 rounded-5 text-center"
        >
          {{ category.category }}
        </h1>
        {% for task in tasks %} {% if category.category == task.category.category and user.username == task.user.username %}
        <div class="card my-3" style="width: 100%">
          <div class="card-body position-relative">
            <span
              data-task-id="{{task.name}}"
              onclick="delete_card(this)"
              class="position-absolute top-0 start-100 translate-middle d-none d-lg-block"
              style="cursor: pointer"
              >&#10005;</span
            >

            <h5 class="card-title">{{ task.name }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">
              {{ task.due_date }}
            </h6>
            <h6 class="card-subtitle mb-2 text-body-secondary">
              {{ task.category }}
            </h6>
            <p class="card-text">{{ task.description }}</p>
            <ul>
              <li>Assigned to: {{ task.user_on_task }}</li>
              <li>Created by: {{ task.user.username }}</li>
            </ul>
            <span
              data-task-id="{{task.name}}"
              onclick="delete_card(this)"
              class="d-block d-md-none"
              style="cursor: pointer"
            >
              Delete This
            </span>
          </div>
        </div>
        {% endif %} {% endfor %}
      </div>
      {%endif%} {% endfor %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js"
      integrity="sha384-RuyvpeZCxMJCqVUGFI0Do1mQrods/hhxYlcVfGPOfQtPJh0JCw12tUAZ/Mv10S7D"
      crossorigin="anonymous"
    ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{%static 'board/board.js'%}"></script>
  </body>
</html>