hometouser/urls.py
from django.urls import path
from . import views

app_name = "hometouser"
urlpatterns = [
    path("", views.index, name="index"),
    path("make-account/", views.make_account, name="make_account"),
    path("<str:display_name>/welcome/", views.home, name="home"),
    path("login/", views.login_user, name="login"),
    path("logged-out/", views.logout_view, name="logout")
]

kanbanboardProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("hometouser.urls")),
    path('board/', include("board.urls")),
    path('', include('board.urls')),
    path('list/', include('list.urls')),
]

list/urls.py
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "list"
urlpatterns = [
    path("", views.list_view, name="list_view"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hometouser/models.py
from django.db import models
from django.contrib.auth.models import User



    

hometouser/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class NameForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1",]

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput)

hometouser/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
from django import forms
from .forms import NameForm, LoginForm
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, "hometouser/index.html")

def make_account(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            # put into database
            user = User(
                username = form.cleaned_data['username'],
                email = form.cleaned_data['email']
            )
            user.set_password(form.cleaned_data['password1'])
            user.save()
            # login so the user is saved and can immediately login
            login(request, user)
            url = reverse("hometouser:home", kwargs={'display_name': user.username})
            return redirect(url)
        else:
            # form invalid — render with errors
            return render(request, "hometouser/make-account.html", {"form": form})

    else:
        form = NameForm()
        return render(request, "hometouser/make-account.html", {"form": form})

def home(response, display_name):
    context = {"display_name" : display_name}
    return render(response, "hometouser/home.html", context)

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                url = reverse("hometouser:home", args=[user.username])
                return redirect(url)
            else:
                url = reverse("hometouser:login")
                return redirect(url)
    else:
        form = LoginForm()
        return render(request, "hometouser/login.html", {"form": form})

def logout_view(request):
    logout(request)
    return render(request, "hometouser/index.html")

hometouser/templates/hometouser/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Kanban Board</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
        <link type="text/css" rel="stylesheet" href="{% static 'hometouser/style.css' %}"/>
    </head>
    <body>
        {%block nav_bar%}
        {%endblock%}

        <div>
            {%block info%}
            {%endblock%}
        </div>
        <div class="mt-5">
            {% block button %}
            {% endblock %}
        </div>

        <div>
            {% block makeform %}
            {% endblock %}
        </div>

        <div>
            {% block loginform %}
            {% endblock %}
        </div>

        <div class="container">
            {% block start_message%}
            {%endblock%}
        </div>

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js" integrity="sha384-RuyvpeZCxMJCqVUGFI0Do1mQrods/hhxYlcVfGPOfQtPJh0JCw12tUAZ/Mv10S7D" crossorigin="anonymous"></script>    


    </body>
</html>

hometouser/templates/hometouser/home.html
{% extends 'hometouser/base.html' %} {% load static %} {%block nav_bar%}
<nav class="navbar navbar-expand-lg bg-body-tertiary py-5">
  <div class="container-fluid">
    <a class="navbar-brand"> Welcome {{user.username}} </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-tem"></li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            id="views"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Views
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/board/">Board</a></li>
            <li><a class="dropdown-item" href="/list">List</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="#">About</a></li>
          </ul>
        </li>
      </ul>

        <a class="btn btn-outline-danger" href="{% url 'hometouser:logout' %}">
          Logout
        </a>
    </div>
  </div>
</nav>
{%endblock%} {% block enter_username %} {{display_name}} {% endblock %} {% block start_message%}
<div class="fs-1 text-center start-message">Cick on views to get started!</div>
<div class="summary">
  <h1>A few things of note</h1>
  <ul>
    <li>When making a task make sure to format the time as the following: mm/dd/yyyy</li>
    <li>Some features are still in development such as removing categories</li>
    <li>The about page has not yet been filled out but coming soon!</li>
  </ul>
</div>

{%endblock%}

hometouser/templates/hometouser/index.html
{% extends "hometouser/base.html" %} {% load static %} {%block info%}
<h1>Welcome to Kanban!</h1>
<div class="row">
  <div class="col-md-4 d-sm-flex align-items-center">
    <img src="{% static 'hometouser/team.png' %}" />
    <p>Organization keeps team morale high</p>
  </div>
  <div class="col-md-4 d-sm-flex align-items-center">
    <img src="{% static 'hometouser/team-ladder.png' %}" />
    <p>
      Adding tasks for everyone to help out with gets big projects done faster
    </p>
  </div>
  <div class="col-md-4 d-sm-flex align-items-center">
    <img class="flex" src="{% static 'hometouser/team-gear.png' %}" />
    <p>A modern visual tool keeps focus on the project.</p>
  </div>
</div>
<div class="row">
  <div class="col-md-4 d-sm-flex align-items-center">
    <img src="{% static 'hometouser/collaboration.png' %}" />
  </div>
  <div class="col-md-4 d-sm-flex align-items-center">
    <img src="{% static 'hometouser/boxycollaboration.jpg' %}" />
  </div>
  <div class="col-md-4 d-sm-flex align-items-center">
    <img src="{% static 'hometouser/purplecollaboration.png' %}" />
  </div>
</div>
{%endblock%} {%block button%}
<div class="d-flex justify-content-center pb-3">
  <div class="login-wrapper">
    <a
      class="col link-secondary btn btn-outline-dark"
      href="{% url 'hometouser:make_account' %}"
      >Make Account</a
    >
  </div>
  <div class="ms-5 login-wrapper">
    <a
      class="col link-secondary btn btn-outline-dark"
      href="{% url 'hometouser:login' %}"
      >Login</a
    >
  </div>
</div>
{% endblock %}

hometouser/templates/hometouser/login.html
{% extends "hometouser/base.html" %}
{% load crispy_forms_tags %}

{% block loginform %}

<div class="d-flex justify-content-center">
    <form action="{% url 'hometouser:login' %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-secondary" type="submit" value="Submit">
    </form>
</div>

{% endblock %}

hometouser/templates/hometouser/make-account.html
{% extends 'hometouser/base.html'%}
{% load crispy_forms_tags %}
{%block makeform%}
<div class="d-flex justify-content-center">
    <form id="make-account-form" action="{% url 'hometouser:make_account' %}"  method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-secondary" type="submit" value="Submit">
    </form>
</div>
{%endblock%}